### ISSUE TITLE
Can't send images

### ISSUE THREAD

**Issue by mifbody** [emes30/facebook_messenger#6]
I'm not having any issues with sending text messages through the notify.messenger but I'm not able to get any pictures to send. I've tried duplicating your YAML in the readme but call service won't send without something in the message field. 

Any ideas?

This won't send because there's no message
```
service: notify.messenger
data:
  target: Brian
  data:
    media: "https://www.decorapark.org/wp-content/uploads/2016/09/cropped-460562_7aa63590c39344a387c9c0d2e2415f5d.jpg"
    media_type: "image/jpeg"
```

**Comment by bogd** [comment]
Long time without a reply... is this repo still alive?!

Anyway, for a long time I have been using this type of call with success:
```
- service: notify.messenger
  data:
    message: 'Some message' # will not be shown, but is mandatory
    data:
      attachment: 
        type: 'image'
        payload: 
           url: https://server.com/url-to-image.jpg
  target:
  - !secret messenger_id
```

This still works with some servers, but for some reason it stopped working when using HA's local webserver. For more details and a workaround, see [here](https://community.home-assistant.io/t/facebook-messenger-no-longer-able-to-send-local-images/719956).
